spring.application.name=bybit-trade
spring.profiles.active=${SPRING_PROFILE:default}
server.port=8888

bybit.api.key=${BYBIT_API_KEY:test_api_key}
bybit.api.secret=${BYBIT_API_SECRET:test_secret_key}
bybit.api.testnet=${BYBIT_TESTNET:false}
min-usdt-amount-for-trade=${MIN_USDT_AMOUNT_FOR_TRADE:50.0}

logging.level.com.mulaczos.bybit_trade.service=INFO

# Dzielnik dla retracementu w strategii scalp
retracement.divider=${RETRACEMENT_DIVIDER:2}