spring.application.name=bybit-trade
spring.profiles.active=${SPRING_PROFILE:default}
server.port=8888

bybit.api.key=${BYBIT_API_KEY:test_api_key}
bybit.api.secret=${BYBIT_API_SECRET:test_secret_key}
bybit.api.testnet=${BYBIT_TESTNET:false}
min-usdt-amount-for-trade=${MIN_USDT_AMOUNT_FOR_TRADE:50.0}

logging.level.com.mulaczos.bybit_trade.service=INFO

# Format logowania
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSSXXX} [%level] %logger{36} : %msg%n

# Dzielnik dla retracementu w strategii scalp
retracement.divider=${RETRACEMENT_DIVIDER:2}

# Konfiguracja Twilio dla powiadomie? SMS
twilio.account.sid=${TWILIO_ACCOUNT_SID:}
twilio.auth.token=${TWILIO_AUTH_TOKEN:}
twilio.phone.number=${TWILIO_PHONE_NUMBER:}
twilio.recipient.phone=${TWILIO_RECIPIENT_PHONE:}

twilio.notifications.enabled=${TWILIO_NOTIFICATIONS_ENABLED:false}

spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB:bybit_trade}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

limit-order.tracker.check-interval=30000