# Konfiguracja serwera
server.port=8888
spring.application.name=bybit-trade

# Konfiguracja bazy danych PostgreSQL dla lokalnego uruchomienia
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfiguracja JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Konfiguracja API Bybit
bybit.api.key=${BYBIT_API_KEY:test_api_key}
bybit.api.secret=${BYBIT_API_SECRET:test_secret_key} 